# Agentic RAG
# Central configuration, loaded from environment variables (.env file).

import os

from dotenv import load_dotenv

load_dotenv()


class Settings:
    # --- Database (PostgreSQL) ---
    DATABASE_URL: str = os.getenv(
        "DATABASE_URL", "postgresql://postgres:postgres@localhost:5432/agentic_rag"
    )

    # --- Connection pooling (psycopg_pool) ---
    # db.get_conn() checks a connection out of a shared pool instead of opening
    # a fresh TCP connection + auth per query (which bottlenecked under load).
    DB_POOL_MIN_SIZE: int = int(os.getenv("DB_POOL_MIN_SIZE", "1"))
    DB_POOL_MAX_SIZE: int = int(os.getenv("DB_POOL_MAX_SIZE", "10"))
    # Seconds get_conn() waits for a free pooled connection before falling back
    # to a one-off direct connection.
    DB_POOL_TIMEOUT: float = float(os.getenv("DB_POOL_TIMEOUT", "5"))

    # --- Embeddings (any litellm-supported model) ---
    # Examples:
    #   "openai/text-embedding-3-small"     (1536 dims, needs OPENAI_API_KEY)
    #   "gemini/text-embedding-004"         (768 dims, needs GEMINI_API_KEY)
    #   "ollama/nomic-embed-text"           (768 dims, local via Ollama)
    #   "mock"                              (no key needed, for offline testing)
    EMBEDDING_MODEL: str = os.getenv("EMBEDDING_MODEL", "mock")
    EMBEDDING_DIM: int = int(os.getenv("EMBEDDING_DIM", "1536"))

    # Vector metric for similarity (must match how the embedding model outputs):
    #   "cosine" - safe default, works for any embeddings.
    #   "dot"    - inner product; FASTEST, but only correct when embeddings are
    #              L2-normalized (OpenAI / nomic / mock all are). Enables HNSW
    #              ip_ops and future int8/bit quantization for speed.
    #   "l2"     - Euclidean distance; for raw/geometric embeddings (images,
    #              unnormalized vectors) where straight-line distance matters.
    # NOTE: the [0,1] cosine-calibrated thresholds (RELEVANCE_FLOOR, cache
    # thresholds, GENERAL_STRONG_THRESHOLD) only hold for cosine and normalized
    # dot; with "l2" they must be re-tuned.
    EMBEDDING_METRIC: str = os.getenv("EMBEDDING_METRIC", "cosine").strip().lower()

    # Asymmetric query/document prefixes: a big retrieval-quality win for
    # sentence-transformers models (BAAI/bge, nomic, all-MiniLM). Usually OFF
    # for API embeddings (OpenAI/Gemini) — keep OFF for those, ON for local/Ollama.
    USE_ASYMMETRIC_PREFIX: bool = os.getenv("USE_ASYMMETRIC_PREFIX", "0") == "1"
    QUERY_PREFIX: str = "Represent the query for retrieving relevant documents: "
    DOC_PREFIX: str = "Represent the document for retrieval: "

    # --- LLM (litellm model strings, ANY provider) ---
    # Examples: "openai/gpt-4o-mini", "gemini/gemini-2.0-flash",
    #           "anthropic/claude-3-5-sonnet", "ollama/llama3"
    #   "mock" = no key needed, for offline testing.
    LLM_MODEL: str = os.getenv("LLM_MODEL", "mock")
    VISION_MODEL: str = os.getenv("VISION_MODEL", "mock")
    TEMPERATURE: float = float(os.getenv("TEMPERATURE", "0.2"))
    MAX_TOKENS: int = int(os.getenv("MAX_TOKENS", "1024"))

    # --- Chunking (defaults: 600/80 = ~13% overlap) ---
    # Smaller, focused chunks (300-800 chars): tighter embedding topics, cleaner
    # sparse/exact-term matches, and more precise citations. Overlap of 10-20%
    # preserves context across chunk boundaries without too much redundancy.
    CHUNK_SIZE: int = int(os.getenv("CHUNK_SIZE", "600"))
    CHUNK_OVERLAP: int = int(os.getenv("CHUNK_OVERLAP", "80"))

    # Short structured documents (resumes, forms, profiles) get LARGER chunks so
    # their sections stay intact and aren't fragmented mid-sentence.
    STRUCTURED_CHUNK_SIZE: int = int(os.getenv("STRUCTURED_CHUNK_SIZE", "1200"))
    STRUCTURED_CHUNK_OVERLAP: int = int(os.getenv("STRUCTURED_CHUNK_OVERLAP", "150"))
    STRUCTURED_MAX_CHARS: int = int(os.getenv("STRUCTURED_MAX_CHARS", "5000"))

    # --- Retrieval ---
    TOP_K: int = int(os.getenv("TOP_K", "6"))
    RELEVANCE_FLOOR: float = float(os.getenv("RELEVANCE_FLOOR", "0.25"))
    RRF_K: int = int(os.getenv("RRF_K", "60"))          # reciprocal-rank fusion constant
    USE_QUERY_EXPANSION: bool = os.getenv("USE_QUERY_EXPANSION", "1") == "1"
    # Multi-turn support: rewrite follow-up questions ("what does it do?") into
    # a standalone, self-contained query using the conversation history BEFORE
    # retrieval + routing, so pronouns/ellipsis resolve against the earlier
    # turns ("What does RAGAS do?"). Off when you only ever ask one-shot.
    USE_QUERY_REWRITE: bool = os.getenv("USE_QUERY_REWRITE", "1") == "1"
    # Total query variants (including the original) generated by LLM expansion.
    # Each is embedded (dense) and run through keyword + sparse, so more
    # variants = better recall at higher cost/latency.
    QUERY_EXPANSION_VARIANTS: int = int(os.getenv("QUERY_EXPANSION_VARIANTS", "5"))
    SEMANTIC_CACHE_THRESHOLD: float = float(os.getenv("SEMANTIC_CACHE_THRESHOLD", "0.90"))
    # A query is treated as "really about a document" only when its top vector
    # match is at least this cosine (gemini-embedding-2: strong ~0.75+, weak ~0.6).
    # Below it, general-knowledge questions fall back to the general model.
    GENERAL_STRONG_THRESHOLD: float = float(os.getenv("GENERAL_STRONG_THRESHOLD", "0.72"))

    # --- Ingestion ---
    MAX_IMAGES_PER_PDF: int = int(os.getenv("MAX_IMAGES_PER_PDF", "20"))
    MAX_IMAGE_DIM: int = int(os.getenv("MAX_IMAGE_DIM", "1200"))
    MAX_PAGES: int = int(os.getenv("MAX_PAGES", "0"))  # 0 = whole document
    # Filenames that signal a short structured doc (resume/form) -> larger chunks.
    # Comma-separated, case-insensitive substring match.
    STRUCTURED_KEYWORDS: str = os.getenv(
        "STRUCTURED_KEYWORDS", "resume,cv,curriculum,profile,form,application")
    # How many texts to embed+store per batch (incremental saving).
    EMBED_BATCH_SIZE: int = int(os.getenv("EMBED_BATCH_SIZE", "32"))

    # --- Uploads (size / count) ---
    # Max size of a single uploaded file in MB (0 = unlimited). Enforced
    # server-side (413) and pre-checked in the UI. Default 50 MB: an unbounded
    # default would let one request read arbitrarily large bodies into memory
    # (DoS); raise it or set 0 only when the deployment is trusted.
    MAX_UPLOAD_MB: int = int(os.getenv("MAX_UPLOAD_MB", "50"))
    # Max files accepted per upload batch/selection (0 = unlimited). Enforced
    # in the UI (extra files are skipped with a notice).
    MAX_UPLOAD_FILES: int = int(os.getenv("MAX_UPLOAD_FILES", "0"))

    # --- Agents / citations ---
    MAX_CRITIC_ROUNDS: int = int(os.getenv("MAX_CRITIC_ROUNDS", "2"))
    # Exact-query LRU cache for the router's LLM classification: repeated
    # questions skip the router's full LLM round-trip (retrieval/semantic
    # caches already short-circuit repeats, but routing runs before them).
    # Temperature-0 classification is deterministic, so caching is safe.
    ROUTER_CACHE_SIZE: int = int(os.getenv("ROUTER_CACHE_SIZE", "256"))
    ROUTER_MAX_TOKENS: int = int(os.getenv("ROUTER_MAX_TOKENS", "100"))
    # Gemini can truncate long JSON verdicts at 300 tokens; 600 leaves room
    # for the full issues[] array and avoids fail-closed critic calls.
    CRITIC_MAX_TOKENS: int = int(os.getenv("CRITIC_MAX_TOKENS", "600"))
    # A "padding" citation is pruned when its chunk shares less than this
    # fraction of the claim's significant words.
    CITATION_OVERLAP_THRESHOLD: float = float(os.getenv("CITATION_OVERLAP_THRESHOLD", "0.25"))
    # Source-card snippets: max characters and the overlap-search window (words).
    SNIPPET_MAX_CHARS: int = int(os.getenv("SNIPPET_MAX_CHARS", "220"))
    SNIPPET_WINDOW: int = int(os.getenv("SNIPPET_WINDOW", "40"))

    # --- Retrieval knobs ---
    # Size of the query-embedding LRU cache (repeated queries never re-embed).
    QUERY_EMBED_CACHE_SIZE: int = int(os.getenv("QUERY_EMBED_CACHE_SIZE", "256"))
    # Keyword search: multiplier applied to a document-title ts_rank match.
    KEYWORD_TITLE_BOOST: float = float(os.getenv("KEYWORD_TITLE_BOOST", "2.0"))
    # Score used for exact file-name matches (promoted to the top of results).
    FILENAME_MATCH_SCORE: float = float(os.getenv("FILENAME_MATCH_SCORE", "3.0"))
    # Fetch N x top_k candidates per search before fusion.
    RETRIEVAL_MULTIPLIER: int = int(os.getenv("RETRIEVAL_MULTIPLIER", "2"))

    # --- Two-stage retrieval: bi-encoder recall + cross-encoder rerank ---
    # Stage 1 (bi-encoder / hybrid + RRF) fetches a WIDE candidate pool fast;
    # stage 2 (cross-encoder) rescores each [query, chunk] pair jointly and
    # picks the final TOP_K. Much more accurate ordering, small latency cost.
    USE_RERANKER: bool = os.getenv("USE_RERANKER", "1") == "1"
    # Any sentence-transformers cross-encoder. Default is the CPU-friendly
    # 0.6B model (matches the README + docker-compose); the 4B is a heavier
    # GPU-only upgrade for offline/batch eval:
    #   "Qwen/Qwen3-Reranker-0.6B"             (default: CPU-friendly, ~1.1GB)
    #   "Qwen/Qwen3-Reranker-4B"               (SOTA multilingual, ~8GB, needs GPU)
    #   "BAAI/bge-reranker-base"               (solid, smaller)
    #   "cross-encoder/ms-marco-MiniLM-L-6-v2" (tiny fallback, ~80MB)
    RERANKER_MODEL: str = os.getenv("RERANKER_MODEL", "Qwen/Qwen3-Reranker-0.6B")
    # Truncation for [query, chunk] pairs. Our chunks run up to ~2500 chars
    # (~600 tokens), so 1024 keeps long structured docs intact (Qwen3 supports 32k).
    RERANKER_MAX_LENGTH: int = int(os.getenv("RERANKER_MAX_LENGTH", "1024"))
    # Optional task instruction for instruction-aware rerankers (Qwen3). When set,
    # it's injected via the model's prompt template (Qwen measures ~1-5% gains).
    # Leave empty to use the model's built-in default instruction.
    RERANKER_INSTRUCTION: str = os.getenv("RERANKER_INSTRUCTION", "")
    # How many fused candidates to send to the cross-encoder. Starting point: 20
    # (matches the README + .env; interactive-friendly with the 0.6B model).
    # Tune after measuring (see benchmark_rerank.py): larger = better recall at
    # higher rerank latency, smaller = faster. Sweep with
    #   python benchmark_rerank.py --sizes 10,25,50,100,200
    RERANKER_CANDIDATES: int = int(os.getenv("RERANKER_CANDIDATES", "20"))
    # Pairs scored per forward pass (lower if GPU/CPU memory is tight).
    RERANKER_BATCH_SIZE: int = int(os.getenv("RERANKER_BATCH_SIZE", "32"))
    # Rerank-confidence floor: cross-encoder candidates whose sigmoid confidence
    # is below this value are dropped from the SERVED pool (clear retrieval
    # noise). 0.0 = disabled (default, current behavior). Measured 2026-08-27 on
    # the E2E judged set: the top-5 pool carries ~0.27 retrieval precision@5; a
    # 0.5 floor raises it to ~0.37 with zero recall loss (relevant chunks are
    # always conf >= 0.99). Residual noise above the floor (topically-similar
    # docs, conf 0.98+) is a 0.6B-reranker limitation the floor cannot remove.
    RERANK_CONFIDENCE_FLOOR: float = float(os.getenv("RERANK_CONFIDENCE_FLOOR", "0.0"))
    # Always serve at least this many chunks (topped up from the best below the
    # floor) so weak matches still give the Writer something to ground on.
    RERANK_CONFIDENCE_MIN_KEEP: int = int(os.getenv("RERANK_CONFIDENCE_MIN_KEEP", "2"))

    # --- Retrieval-results cache (popular queries) ---
    # Caches the RERANKED chunk list per query, so common questions skip the
    # expensive stage 1 (hybrid search + RRF) and stage 2 (cross-encoder)
    # entirely. The LLM answer is still generated fresh from the cached chunks.
    RETRIEVAL_CACHE_ENABLED: bool = os.getenv("RETRIEVAL_CACHE_ENABLED", "1") == "1"
    # Cosine threshold for a hit: only near-identical rephrases are served from
    # cache (deliberately HIGH, unlike the response semantic cache) so distinct
    # questions never share a reranked slot.
    RETRIEVAL_CACHE_THRESHOLD: float = float(os.getenv("RETRIEVAL_CACHE_THRESHOLD", "0.97"))
    # Max entries; when exceeded the least-popular / least-recently-used rows
    # are evicted.
    RETRIEVAL_CACHE_MAX_ENTRIES: int = int(os.getenv("RETRIEVAL_CACHE_MAX_ENTRIES", "500"))

    # --- BM25-style sparse retrieval (pgvector sparsevec) ---
    # Catches EXACT terms (names, codes, acronyms, IDs) that dense embeddings
    # miss; fused with dense + full-text via RRF. Requires pgvector >= 0.7.
    USE_SPARSE_SEARCH: bool = os.getenv("USE_SPARSE_SEARCH", "1") == "1"
    # Max distinct terms in the vocabulary (sparsevec dimension, 1-based idx).
    SPARSE_DIM: int = int(os.getenv("SPARSE_DIM", "16000"))
    # Max non-zero entries kept per chunk (bounds index size; HNSW caps at 1000).
    SPARSE_TOP_TERMS: int = int(os.getenv("SPARSE_TOP_TERMS", "256"))

    # --- Retrieval channels (A/B toggle) ---
    # Full-text search (ts_rank / to_tsvector) channel. Dense + sparse are
    # always on; toggle FTS to A/B "dense+sparse" vs "dense+fts+sparse":
    #   USE_KEYWORD_SEARCH=0  -> dense + sparse only
    #   USE_KEYWORD_SEARCH=1  -> dense + fts + sparse (default)
    USE_KEYWORD_SEARCH: bool = os.getenv("USE_KEYWORD_SEARCH", "1") == "1"

    # --- Metadata filtering ---
    # Where metadata filters are applied:
    #   "pre"  - WHERE clause BEFORE the ANN scan (fast; but selective filters
    #            can cut ANN results -> recall risk)
    #   "post" - fetch top_k x METADATA_FILTER_OVERSAMPLE unfiltered, then trim
    #            in Python (guaranteed recall; scans more)
    METADATA_FILTER_MODE: str = os.getenv("METADATA_FILTER_MODE", "pre").strip().lower()
    # Oversampling factor used when post-filtering.
    METADATA_FILTER_OVERSAMPLE: int = int(os.getenv("METADATA_FILTER_OVERSAMPLE", "5"))

    # --- Conversation memory ---
    MEMORY_RECENT_K: int = int(os.getenv("MEMORY_RECENT_K", "8"))
    MEMORY_RELEVANT_K: int = int(os.getenv("MEMORY_RELEVANT_K", "4"))

    # --- Vision / images ---
    IMAGE_JPEG_QUALITY: int = int(os.getenv("IMAGE_JPEG_QUALITY", "85"))
    VISION_SUMMARY_MAX_TOKENS: int = int(os.getenv("VISION_SUMMARY_MAX_TOKENS", "500"))

    # --- pgvector ---
    # The `vector` type's HNSW index supports at most this many dimensions
    # (pgvector platform limit). Above it we store embeddings as `halfvec`
    # (HNSW cap 4000) so fast indexing still works.
    HNSW_VECTOR_DIM_LIMIT: int = int(os.getenv("HNSW_VECTOR_DIM_LIMIT", "2000"))

    # --- MongoDB (users, sessions & chat history) ---
    # RAG data (documents/chunks/collections/cache) stays in PostgreSQL/pgvector.
    MONGO_URI: str = os.getenv("MONGO_URI", "mongodb://127.0.0.1:27017")
    MONGO_DB: str = os.getenv("MONGO_DB", "agentic_rag")
    SESSION_TTL_SECONDS: int = int(os.getenv("SESSION_TTL_SECONDS", "2592000"))  # 30 days

    # --- Auth rate limiting ---
    # Max login/register attempts per client IP within AUTH_RATE_WINDOW seconds
    # before the endpoint returns 429 (basic brute-force throttling). NOTE: the
    # window is per-process; under `uvicorn --workers N` each worker keeps its
    # own counter, so the effective limit is N x the configured value.
    AUTH_RATE_LIMIT: int = int(os.getenv("AUTH_RATE_LIMIT", "10"))
    AUTH_RATE_WINDOW: int = int(os.getenv("AUTH_RATE_WINDOW", "60"))

    # --- Auth hardening ---
    # Minimum accepted password length (register + change-password). PBKDF2 is
    # fine for a demo; for production consider a memory-hard KDF (Argon2id /
    # scrypt) — hashlib.scrypt is stdlib and a drop-in if you want it.
    AUTH_MIN_PASSWORD_LEN: int = int(os.getenv("AUTH_MIN_PASSWORD_LEN", "8"))
    # PBKDF2-HMAC-SHA256 work factor. ~600k iterations costs ~0.3-0.6s per
    # attempt (far slower to brute-force than 100k). Tests lower this via env.
    PBKDF2_ITERATIONS: int = int(os.getenv("PBKDF2_ITERATIONS", "600000"))
    # Only honor X-Forwarded-For when behind a trusted reverse proxy that
    # strips/replaces it (nginx, Cloudflare, ...). Off by default so a client
    # cannot spoof its IP and bypass the auth rate limit.
    TRUST_PROXY_HEADERS: bool = os.getenv("TRUST_PROXY_HEADERS", "0") == "1"

    # --- Web / API ---
    # CORS allowed origins (comma-separated). The web UI is served same-origin
    # (via /static), so this only matters for a separate frontend or browser-
    # based OpenAI-compatible clients. Auth uses bearer tokens (NOT cookies),
    # so allow_credentials stays off and "*" is acceptable; restrict it to your
    # frontend origin(s) in production.
    CORS_ORIGINS: str = os.getenv("CORS_ORIGINS", "*")
    # Hard cap on ?limit= for list endpoints — stops one request from pulling
    # the whole table into memory. Clients may request up to this many rows.
    PAGE_LIMIT_CAP: int = int(os.getenv("PAGE_LIMIT_CAP", "1000"))


settings = Settings()

# Fail fast on an invalid similarity metric: an unknown value would otherwise
# silently fall back to cosine and produce confusing rankings / mismatched
# HNSW opclasses.
_VALID_METRICS = ("cosine", "dot", "l2")
if settings.EMBEDDING_METRIC not in _VALID_METRICS:
    raise ValueError(
        f"Invalid EMBEDDING_METRIC={settings.EMBEDDING_METRIC!r}. "
        f"Must be one of: {', '.join(_VALID_METRICS)}.\n"
        "  cosine - safe default, any embeddings\n"
        "  dot    - L2-normalized text embeddings (fastest)\n"
        "  l2     - raw/geometric or image embeddings"
    )
